// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200628222002_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Domain.Meals.Meal", b =>
                {
                    b.Property<string>("CreatorId");

                    b.Property<int>("MealTypeId");

                    b.Property<int>("Calories");

                    b.Property<string>("Description");

                    b.Property<int>("Id");

                    b.Property<string>("Title");

                    b.HasKey("CreatorId", "MealTypeId");

                    b.HasIndex("MealTypeId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Domain.Meals.MealPlan", b =>
                {
                    b.Property<string>("CreatorId");

                    b.Property<int>("Calories");

                    b.Property<string>("Description");

                    b.Property<int>("Id");

                    b.Property<string>("Title");

                    b.HasKey("CreatorId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("Domain.Meals.MealPlanMeals", b =>
                {
                    b.Property<int>("MealId");

                    b.Property<int>("MealPlanId");

                    b.HasKey("MealId", "MealPlanId");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanMeals");
                });

            modelBuilder.Entity("Domain.Meals.MealType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("MealTypes");
                });

            modelBuilder.Entity("Domain.Meals.UserMealPlans", b =>
                {
                    b.Property<int>("MealPlanId");

                    b.Property<string>("AppUserId");

                    b.Property<int>("Id");

                    b.HasKey("MealPlanId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("UsersMealPlans");
                });

            modelBuilder.Entity("Domain.Meals.UserMeals", b =>
                {
                    b.Property<int>("MealId");

                    b.Property<string>("AppUserId");

                    b.Property<int>("Id");

                    b.HasKey("MealId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("UsersMeals");
                });

            modelBuilder.Entity("Domain.User.ActivityFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<float>("Multiplier");

                    b.HasKey("Id");

                    b.ToTable("ActivitiesFactor");
                });

            modelBuilder.Entity("Domain.User.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.User.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LongDescription");

                    b.Property<int>("Multiplier");

                    b.Property<string>("ShortDescription");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Domain.User.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Multiplier");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Domain.User.HeightUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("HeightUnits");
                });

            modelBuilder.Entity("Domain.User.UserStat", b =>
                {
                    b.Property<string>("AppUserId");

                    b.Property<int>("GoalId");

                    b.Property<int>("GenderId");

                    b.Property<int>("ActivityFactorId");

                    b.Property<int>("HeightUnitId");

                    b.Property<int>("WeightUnitId");

                    b.Property<int>("Calories");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<double>("Height");

                    b.Property<int>("Id");

                    b.Property<double>("Weight");

                    b.HasKey("AppUserId", "GoalId", "GenderId", "ActivityFactorId", "HeightUnitId", "WeightUnitId");

                    b.HasIndex("ActivityFactorId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("GoalId");

                    b.HasIndex("HeightUnitId");

                    b.HasIndex("WeightUnitId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("Domain.User.WeightUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("WeightUnits");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Meals.Meal", b =>
                {
                    b.HasOne("Domain.User.AppUser", "Creator")
                        .WithMany("CreatedMeals")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Meals.MealType", "MealType")
                        .WithMany("Meals")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Meals.MealPlan", b =>
                {
                    b.HasOne("Domain.User.AppUser", "Creator")
                        .WithMany("CreatedMealPlans")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Meals.MealPlanMeals", b =>
                {
                    b.HasOne("Domain.Meals.Meal", "Meal")
                        .WithMany("MealPlansMeals")
                        .HasForeignKey("MealId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Meals.MealPlan", "MealPlan")
                        .WithMany("MealPlansMeals")
                        .HasForeignKey("MealPlanId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Meals.UserMealPlans", b =>
                {
                    b.HasOne("Domain.User.AppUser", "AppUser")
                        .WithMany("SavedMealPlans")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Meals.MealPlan", "MealPlan")
                        .WithMany("UserMealPlans")
                        .HasForeignKey("MealPlanId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Meals.UserMeals", b =>
                {
                    b.HasOne("Domain.User.AppUser", "AppUser")
                        .WithMany("SavedMeals")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Meals.Meal", "Meal")
                        .WithMany("UserMeals")
                        .HasForeignKey("MealId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.User.UserStat", b =>
                {
                    b.HasOne("Domain.User.ActivityFactor", "ActivityFactor")
                        .WithMany("UserStats")
                        .HasForeignKey("ActivityFactorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.AppUser", "AppUser")
                        .WithOne("UserStat")
                        .HasForeignKey("Domain.User.UserStat", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.Gender", "Gender")
                        .WithMany("UserStats")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.Goal", "Goal")
                        .WithMany("UserStats")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.HeightUnit", "HeightUnit")
                        .WithMany("UserStats")
                        .HasForeignKey("HeightUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.WeightUnit", "WeightUnit")
                        .WithMany("UserStats")
                        .HasForeignKey("WeightUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
